// Semantic Types for NeuroCanvas Semantic Constellation Engine

import type { Point } from './canvas'

// ═══════════════ UTILITIES ═══════════════

/**
 * FNV-1a hash for quick content change detection.
 * Returns a 32-bit unsigned integer.
 */
export function fnv1aHash(str: string): number {
  let hash = 0x811C9DC5
  for (let i = 0; i < str.length; i++) {
    hash ^= str.charCodeAt(i)
    hash = Math.imul(hash, 0x01000193)
  }
  return hash >>> 0
}

// ═══════════════ NODE SEMANTIC DATA ═══════════════

export interface NodeSemanticData {
  nodeId: string
  embedding: number[]
  embeddingVersion: number
  updatedAt: number
  contentHash: number
  clusterId: string | null
}

// Sparse similarity entry (only store pairs above threshold)
export interface SimilarityEntry {
  nodeId: string
  similarity: number
}

// ═══════════════ FIELD VISUALIZATION ═══════════════

export interface FieldLine {
  id: string
  sourceId: string
  targetId: string
  sourcePoint: Point
  targetPoint: Point
  similarity: number
  // Control points for curved lines
  controlPoint1?: Point
  controlPoint2?: Point
}

/** Extended field line with animation properties */
export interface AnimatedFieldLine extends FieldLine {
  opacity: number
  targetOpacity: number
  fadeStartTime: number
  lineWidth: number
}

export interface FieldParticle {
  id: string
  lineId: string
  progress: number // 0-1 along the line
  speed: number
  size: number
  opacity: number
}

export interface ResonancePulse {
  id: string
  nodeId: string
  center: Point
  radius: number
  maxRadius: number
  opacity: number
  startTime: number
}

// ═══════════════ CLUSTERS ═══════════════

export interface SemanticCluster {
  id: string
  nodeIds: string[]
  centroid: Point
  radius: number
  averageSimilarity: number
  dominantCategory: string | null
  keywords: string[]
}

// ═══════════════ FIELD INTERACTION ═══════════════

export interface FieldInteractionState {
  hoveredNodeId: string | null
  highlightedLineIds: Set<string>
  dimmedLineIds: Set<string>
  showSimilarityLabels: boolean
}

// ═══════════════ SEARCH ═══════════════

export interface SemanticSearchResult {
  nodeId: string
  content: string
  similarity: number
  matchType: 'exact' | 'semantic' | 'hybrid'
}

// ═══════════════ INSIGHTS ═══════════════

export type InsightType =
  | 'bridge'
  | 'gap'
  | 'outlier'
  | 'cluster'
  | 'conceptual-gap'
  | 'structural-suggestion'
  | 'balance-issue'
  | 'deepening-opportunity'
  | 'accuracy-concern'
  | 'hub-node'
  | 'dead-end'
  | 'chain-risk'
  | 'imbalanced-cluster'
  | 'orphan-cluster'

export interface Insight {
  id: string
  type: InsightType
  title: string
  description: string
  confidence: number // 0-1
  relatedNodeIds: string[]
  suggestedPosition?: Point
  suggestedContent?: string
  suggestedConnections?: Array<{
    sourceId: string
    targetId: string
  }>
  createdAt: number
}

/**
 * Enriched insight with actionable suggestions (v2)
 */
export interface EnrichedInsight extends Insight {
  /** Suggested action to take (e.g. "add-node", "add-connection", "restructure") */
  suggestedAction?: 'add-node' | 'add-connection' | 'restructure' | 'merge' | 'expand' | 'delete'
  /** Payload for the action (depends on suggestedAction) */
  actionPayload?: Record<string, unknown>
  /** LLM reasoning for this insight */
  reasoning?: string
  /** Whether this was generated by LLM (true) or heuristic (false) */
  isLLMGenerated?: boolean
}

// ═══════════════ AI STATE ═══════════════

export type AIStatus = 'idle' | 'loading-model' | 'computing' | 'ready' | 'error'

export interface AIState {
  status: AIStatus
  modelLoaded: boolean
  modelProgress: number // 0-100 for loading progress
  hasWebGPU: boolean
  backendType: 'native' | 'web' | null
  error?: string
  lastEmbeddingTime?: number // ms for last embedding computation
}

// ═══════════════ PROCESSOR STATE ═══════════════

export type ProcessorState = 'idle' | 'embedding' | 'similarity' | 'clustering' | 'insights'

// ═══════════════ FIELD SETTINGS ═══════════════

export interface FieldSettings {
  enabled: boolean
  intensity: number // 0-1, controls opacity/visibility
  showParticles: boolean
  showPulses: boolean
  similarityThreshold: number // 0-1, minimum similarity to show field line
  maxFieldLines: number
  maxParticles: number
  showClusterGlow: boolean
  showClusterLabels: boolean
  interactiveExploration: boolean
  adaptiveLineCount: boolean
  embeddingBatchSize: number
}

// Default field settings
export const DEFAULT_FIELD_SETTINGS: FieldSettings = {
  enabled: false,
  intensity: 0.7,
  showParticles: true,
  showPulses: true,
  similarityThreshold: 0.5,
  maxFieldLines: 50,
  maxParticles: 200,
  showClusterGlow: true,
  showClusterLabels: true,
  interactiveExploration: false,
  adaptiveLineCount: true,
  embeddingBatchSize: 16
}

// ═══════════════ DATABASE TYPES ═══════════════

export interface DBSemanticData {
  id: string // composite: `${mapId}-${nodeId}`
  nodeId: string
  mapId: string
  embedding: number[] // 256d (Matryoshka-truncated nomic-embed-text-v1.5)
  embeddingVersion: number
  updatedAt: number
}

// ═══════════════ WORKER MESSAGE TYPES ═══════════════

export type SemanticWorkerMessageType =
  | 'init'
  | 'expand'
  | 'embed'
  | 'embed-batch'
  | 'compute-similarities'
  | 'update-similarities'
  | 'detect-clusters'
  | 'hybrid-search'
  | 'benchmark-batch-size'
  | 'search'
  | 'suggest'
  | 'dispose'
  | 'progress'

export interface EmbedBatchPayload {
  texts: Array<{
    id: string
    text: string
    contentHash?: number
  }>
}

export interface EmbedBatchResult {
  embeddings: Array<{
    id: string
    embedding: number[]
  }>
  dimensions: number
}

export interface ComputeSimilaritiesPayload {
  embeddings: Array<{
    id: string
    embedding: number[]
  }>
  threshold: number
}

export interface ComputeSimilaritiesResult {
  similarities: Array<{
    sourceId: string
    targetId: string
    similarity: number
  }>
}

export interface UpdateSimilaritiesPayload {
  changedNodeIds: string[]
  embeddings: Array<{
    id: string
    embedding: number[]
  }>
  currentSimilarities: Array<{
    sourceId: string
    targetId: string
    similarity: number
  }>
  threshold: number
}

export interface UpdateSimilaritiesResult {
  similarities: Array<{
    sourceId: string
    targetId: string
    similarity: number
  }>
}

export interface DetectClustersPayload {
  embeddings: Array<{
    id: string
    embedding: number[]
  }>
  similarities: Array<{
    sourceId: string
    targetId: string
    similarity: number
  }>
  minClusterSize: number
  minSimilarity: number
}

export interface DetectClustersResult {
  clusters: SemanticCluster[]
}

export interface HybridSearchPayload {
  query: string
  nodes: Array<{
    id: string
    content: string
    embedding: number[]
  }>
  topK: number
}

export interface HybridSearchResult {
  results: SemanticSearchResult[]
}

export interface BenchmarkBatchSizeResult {
  optimalBatchSize: number
  results: Array<{
    batchSize: number
    throughput: number
    avgTime: number
  }>
}
